### ISSUE TITLE
Meeting on Wed 14th September

### ISSUE THREAD

**Issue by sofiapoh** [CYPIAPT-LNDSE/breathing-with-kitty#37]
So if you want to make any changes to the readme or would like us to tweak something about the wireframes let us know here!

**Comment by CharlotteBarrett** [comment]
Hi @sofiapoh - I'm sorry but I won't be able to make the 5pm meeting. You won't believe this but our office has been evacuated due to a gas leak! I have no access to Internet other than by my phone. Please can you upload changes here so I can view when I get home tonight and then we can have a final call in the morning at say 10am? Is that okay?

**Comment by CharlotteBarrett** [comment]
Am heading home now so might be able to review at 5.30 if you are around then?

**Comment by sofiapoh** [comment]
Oh sorry I just sent you this before I saw this, hope everything is okay! All is going well in terms of development so if you can't make it for chat tonight don't worry. See you tomorrow!

**Comment by sofiapoh** [comment]
We will be here at 5:30.
